name: Auto Merge on Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Merge Pull Request
      uses: "peter-evans/merge-pull-request@v4"
      with:
        pull-request: ${{ github.event.pull_request.number }}
        merge-method: squash  # Choose 'merge', 'squash', or 'rebase'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
